version: '3.8'

services:
  backend:
    build: .
    container_name: ninja-backend
    ports:
      - "8080:8080"
    volumes:
      - ninja-data:/app/data
    restart: always

  frontend:
    build: ./frontend-ninjas  # Ajuste para o nome da pasta onde está o seu front-end
    container_name: ninja-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  ninja-data: