#pring.application.name=CadastroDeNinjas
#spring.config.import=optional:file:.env[.properties]

#spring.datasource.url=${DATABASE_URL}
#spring.datasource.driver=org.h2.Driver
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}


#Config do JPA // hibernates
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.h2.console.enabled=true

#Config o flyway
#spring.flyway.enable=true
#spring.flyway.locations=classpath:db/migrations
#spring.flyway.baseline-on-migrate=true

#MODELO SQL -> NOVO MODELO

# Configuração do MySQL com Variáveis de Ambiente
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Com o Flyway ativo, o Hibernate deve apenas VALIDAR se as entidades batem com o banco
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuração do Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=true
spring.flyway.clean-disabled=false

spring.flyway.clean-on-validation-error=true